sudo: false
os:
 - linux
 - osx
language: d
d:
 - dmd-2.071.1
 - ldc-1.1.0-beta2
env:
 - ARCH="x86_64" CONF=""
 - ARCH="x86_64" CONF="-sse42"
matrix:
  include:
    - {os: linux, d: dmd-2.071.1, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.1.0-beta2, env: ARCH="x86" CONF="", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc-1.1.0-beta2, env: ARCH="x86" CONF="-sse42", addons: {apt: {packages: [[gcc-multilib]]}}}
branches:
  only:
    - master
script:
 - echo $ARCH
 - dub test --arch=$ARCH --build=unittest$CONF
after_success:
 - bash <(curl -s https://codecov.io/bash)
